import React from 'react';
import {Suggester} from './Suggester';

function App() {
    let stupidQuestions = [
        'What is the length of spaghetti?',
        'How can I grow taller?',
        'Does the Mandela Effect confirm the existence of a parallel universe?',
        'Can helicopters fly upside down?',
        'What is the lifespan of a mayfly?',
        'How do I get my husband a brain transplant?',
        'Who let the dogs out?',
        'What percentage of people have seen a ghost?',
        'What is the funniest joke in the world?',
        'Where are my keys?',
        'How many toes does a rhinoceros have?',
        'Why is your face on your head?',
        'Why does cucumber taste like shampoo?',
        'What is the average weight of a panda?',
        'Should I tell my parents I’m adopted?',
        'Do midgets have night vision?',
        'If i eat myself will I get twice as big or disappear completely?',
        'Does it take 18 months for twins to be born? Or 9?',
        'Do you think NASA invented thunderstorms to cover up the sound of space battles?',
        'I swallowed an ice cube whole, and I haven’t pooped it out?',
        'How big is the specific ocean?',
        'How am I sure i’m the real mom of my kid?',
        'Is there a pill that’ll make me gay?',
        'How do I ask a question on Yahoo Answers? (This was asked on Yahoo! Answers.)',
        'Why are the holes in cats fur always in the right places for their eyes?',
        'Wtf is obamas last name? Does anyone know?',
        'How far of a drive is it from Miami to Florida?',
        'what does a quarter till 4 mean? like, why is it called that?! cause a quarter is worth 25 cents, so why is it 15 min?!',
        'I’m so lost! Isn’t NFL just for the U.S?! How does New England have a team??????',
        'is african a religion?',
        'Are chickens considered animals or birds?',
        'IS IT POSSIBLE FOR TATTOS TO GET PASSED ON GENETICALLY FROM PARENT TO CHILD?',
        'If I shave my golden retriever like a lion, will the other dogs respect him more?',
        'Can your baby get preganent if you have sex while preganent?',
        'Where do lost socks go when they go missing?',
        'What happens to the people born on Feb.. 29????? do the stay one until 4 years past??',
        'Does looking at a picture of the sun hurt your eyes?',
        'At what age does a boy period start?',
        'Why doesn’t the Earth fall down?',
        'If batman parents are died, then how was he born?',
        'Is an egg a fruit or a vegetable?',
        'Is whale sperm the reason why the ocean so salty?',
        'do babies poop in the womb',
        'what would happen if I hired two private investigators to follow each other',
        'Can blind people see their dreams?',
        'Why is it called ‘shipping’ if it goes by truck? Why is it called ‘cargo’ when it goes by ship?',
        'How do bankruptcy attorneys make any money?',
        'If an ambulance hits someone on the road while transporting someone to a hospital, do they bring that person with them too?',
        'If a doctor has a heart attack while performing a surgery, will the other doctors and nurses present work on him first?',
        'If you throw your cat outside, will it be called kitty litter?',
        'If roses are red, why are violets blue?',
        'If a Smurf starts to choke, what color it will it become?',
        'If prunes are dried plums, where do they get prune juice from?',
        'Why do they say ‘like taking candy from a baby’ when babies tend to be greedy with candy? Wouldn’t it be easier to take money from a baby?',
        'Why do round pizzas come in square boxes?',
        'Why do we say that an alarm clock goes ‘off’ when it actually tuns on?',
        'If someone owns a piece of land, how deep does their ownership go? Do they own it all the way to the center of the earth?',
        'Do hummingbirds hum because they can’t remember any of the words?',
        'Is it possible to see someone’s tears underwater?',
        'Why are there things called unsolved mysteries? Shouldn’t they be unsolved in the first place to be called a mystery?',
        'Do penguins have knees?',
        'Why do they say ‘giving my two cents’ when it’s only a penny for your thoughts?',
        'If you pamper a cow and give it lots of stuff, does it produce spoiled milk?',
        'Why is drowsiness listed as a side-effect for sleeping pills?',
        'What was the first person to milk a cow trying to do?',
        'Who came up with names for things? Like, who stood in front of a door and said ‘hmm, this is a door’?',
        'Why is it that when people are asked what they would bring to a deserted island, they never answer ‘a boat’?',
        'Do mermaids give birth to live children or do they lay eggs?',
        'Do Roman nurses and health care workers refer to an IV as a four?',
        'What symbol represents zero in the roman numerals?',
        'If people from Poland are called Poles, do you call people from Holand ‘Holes’?',
        'Why are chickpeas called chickpeas when they’re neither chicks nor peas?',
        'Why do the words ‘overlook’ and ‘oversee’ mean different things when look and see are nearly synonyms?',
        'If a person suffering from amnesia was suddenly cured, would they remember that they had no memory?',
        'Where did dictionary makers look to find the meanings for the words before dictionaries were in existence?',
        'Why do we say ‘after dark’ when it’s actually really after light?',
        'Do you need to set an appointment to see a psychic or will they be expecting you?',
        'Why does a grapefruit look and taste nothing like a grape?',
        'Why are there self-help groups if it’s supposed to be SELF help?',
        'Is the sea salty because the shore never waves back?',
        'If an unidentified flying object fell to the ground and people were able to identify what it was, would it be called a flying object?',
        'What do you call a male lady bug?',
        'Can atheists get insurance policies that cover acts of God?',
        'If you can say that you’re speechless, doesn’t that mean that you were able to talk, and are thus, not speechless?',
        'What makes the difference between a wise man and a wise guy?',
        'Why do we say that something is ‘out of whack’? what is a whack in the first place?',
        'Why do people say that something sells like ‘hotcakes’ if they sell out fast? How fast do hotcakes sell?',
        'Why do we say that we have the weight of the world on our shoulders, but when we try to express it, we say we have to get it off of our chests?',
        'If you decide to describe yourself as indecisive, are you decisive or indecisive?',
        'Why is room temperature used as a measurement of warmth when not all rooms have the same temperature?',
        'What does ‘ok’ actually mean?',
        'Why do super heroes wear their underwear outside of their clothes?',
        'If eating your dessert before a meal will spoil your appetite, then won’t eating a meal before your dessert ruin your appetite for dessert?',
        'Why do women and men’s shoe sizes have to be different? Why can’t it be one size chart that just goes through all foot sizes?',
        'Why didn’t they list the word ‘gullible’ in the dictionary?',
        'Is it possible to blow up a balloon while you’re under water?',
        'Why is it that you can’t hum while your nose is plugged? Do we hum through our mouths or through our noses?',
        'Why do we say that people work like a dog if they work all day when all dogs do is lie around?',
        'Do people with a stutter also stutter in their thoughts?',
        'If all of the world is in debt, where did that money go? Who do we owe money to?',
        'Why is it necessary to nail down a coffin’s lid? Are we expecting what’s inside to try to break free?',
        'If a boy named after his dad is called junior, what do you call a girl named after her mom?',
        'Why did they name Donkey Kong that way if he’s a monkey and not a donkey?',
        'When they say that a specific dog food has a new and improved flavor, who tests it?',
        'If a piece of gum is 10 calories, does that include just the chewing or if you swallow it, too?',
    ];
    return (
        <div className='flex justify-center h-screen mt-60'>
            <Suggester suggestions={stupidQuestions} />
        </div>
    );
}

export default App;
